-- =============================================================================
-- Migration: V2__soc2_security_hardening.sql
-- Purpose: Non-destructive database migration for SOC 2 security controls
-- Controls: 1, 3, 4, 6, 7, 9, 10, 14
-- Database: PostgreSQL 18
-- =============================================================================

-- 1. Hardening add_user table (Staff / Administrators)
ALTER TABLE IF EXISTS add_user
    ADD COLUMN IF NOT EXISTS failed_login_attempts INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS account_locked BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS account_locked_until TIMESTAMP WITHOUT TIME ZONE,
    ADD COLUMN IF NOT EXISTS last_failed_login TIMESTAMP WITHOUT TIME ZONE,
    ADD COLUMN IF NOT EXISTS mfa_enabled BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS mfa_secret VARCHAR(255),
    ADD COLUMN IF NOT EXISTS mfa_backup_codes TEXT,
    ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'ACTIVE';

-- 2. Hardening user_register table (End Users / Consumers)
ALTER TABLE IF EXISTS user_register
    ADD COLUMN IF NOT EXISTS role VARCHAR(255) DEFAULT 'USER',
    ADD COLUMN IF NOT EXISTS failed_login_attempts INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS account_locked BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS account_locked_until TIMESTAMP WITHOUT TIME ZONE,
    ADD COLUMN IF NOT EXISTS last_failed_login TIMESTAMP WITHOUT TIME ZONE,
    ADD COLUMN IF NOT EXISTS mfa_enabled BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS mfa_secret VARCHAR(255),
    ADD COLUMN IF NOT EXISTS mfa_backup_codes TEXT,
    ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'ACTIVE';

-- 3. Ensure audit_log table exists with necessary security monitoring fields
CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(255),
    description VARCHAR(1000),
    http_method VARCHAR(255),
    ip_address VARCHAR(255),
    module VARCHAR(255),
    request_url VARCHAR(255),
    role VARCHAR(255),
    status VARCHAR(255),
    timestamp TIMESTAMP WITHOUT TIME ZONE,
    username VARCHAR(255)
);

-- 4. Create performance and security audit indexes
CREATE INDEX IF NOT EXISTS idx_audit_log_timestamp ON audit_log (timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_audit_log_username ON audit_log (username);
CREATE INDEX IF NOT EXISTS idx_audit_log_action ON audit_log (action);
CREATE INDEX IF NOT EXISTS idx_add_user_username ON add_user (username);
CREATE INDEX IF NOT EXISTS idx_user_register_username ON user_register (username);
